controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    # Controller definitions
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

# Parameters for the differential drive controller
diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    # Physical properties of the robot
    wheel_separation: 0.35 # meters
    wheel_radius: 0.075    # meters

    # Other controller parameters
    publish_rate: 50.0 # Hz, for odom topic
    odom_frame_id: odom
    base_frame_id: base_link
    use_stamped_vel: false

